language: java
before_script:
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS
jdk:
  - oraclejdk8
#  - oraclejdk8
#script: mvn -Pitest -DargLine="-Dcom.basho.riak.search=true -Dcom.basho.riak.2i=true" clean verify
script: mvn clean install